-- ============================================================
-- Chatrium AI Communication Assistant — MySQL schema
-- Target: MySQL 8.0+ on Hostinger managed DB
-- Database: chatrium_ai
-- ============================================================

CREATE DATABASE IF NOT EXISTS chatrium_ai
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE chatrium_ai;

-- ------------------------------------------------------------
-- 1. users
-- One row per Chatrium employee with access to the app.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email           VARCHAR(255) NOT NULL,
  name            VARCHAR(120) NULL,
  role            VARCHAR(60)  NOT NULL DEFAULT 'staff',
    -- enum-like: 'general_manager', 'front_office_manager',
    --           'sales_marketing', 'reservations',
    --           'guest_relations', 'staff', 'marcom_admin', 'it_admin'
  property        VARCHAR(60)  NOT NULL DEFAULT 'rawai',
    -- 'rawai', 'grand_bangkok', 'riverside_bangkok',
    -- 'maitria_rama9', 'maitria_sukhumvit18'
  is_active       TINYINT(1) NOT NULL DEFAULT 1,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at   DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 2. login_tokens
-- Magic-link tokens. Hashed at rest.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS login_tokens (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id         BIGINT UNSIGNED NOT NULL,
  token_hash      CHAR(64) NOT NULL,                   -- SHA-256 hex
  expires_at      DATETIME NOT NULL,
  used            TINYINT(1) NOT NULL DEFAULT 0,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_login_tokens_user (user_id),
  KEY idx_login_tokens_hash (token_hash),
  CONSTRAINT fk_login_tokens_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 3. brand_voice_prompts
-- Versioned system prompt. Never UPDATE in place — INSERT new row.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS brand_voice_prompts (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  version         VARCHAR(20)  NOT NULL,               -- 'v1.0', 'v1.1', ...
  prompt_text     MEDIUMTEXT   NOT NULL,
  is_active       TINYINT(1)   NOT NULL DEFAULT 0,
  notes           VARCHAR(500) NULL,
  created_by      VARCHAR(120) NULL,                   -- email of MARCOM editor
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_prompt_version (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed the initial prompt (paste actual text from BRAND_VOICE_PROMPT.md)
-- INSERT INTO brand_voice_prompts (version, prompt_text, is_active, created_by)
-- VALUES ('v1.0', '<<< paste here >>>', 1, 'sakchai.nim@chatrium.com');

-- ------------------------------------------------------------
-- 4. drafts
-- Every email draft generated by the system.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS drafts (
  id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  draft_uid           CHAR(26) NOT NULL,               -- ULID, exposed externally
  user_id             BIGINT UNSIGNED NOT NULL,
  property            VARCHAR(60)  NOT NULL,
  task_type           VARCHAR(40)  NOT NULL,
  recipient_name      VARCHAR(200) NULL,
  recipient_context   TEXT NULL,
  input_language      ENUM('th','en') NOT NULL DEFAULT 'en',
  objective           TEXT NOT NULL,
  additional_notes    TEXT NULL,
  template_id         BIGINT UNSIGNED NULL,
  prompt_version      VARCHAR(20) NOT NULL,
  generated_subject   VARCHAR(255) NULL,
  generated_body      MEDIUMTEXT NULL,
  qc_no_em_dash       TINYINT(1) NOT NULL DEFAULT 1,
  qc_no_slang         TINYINT(1) NOT NULL DEFAULT 1,
  qc_cta_present      TINYINT(1) NOT NULL DEFAULT 1,
  qc_loyalty_ok       TINYINT(1) NOT NULL DEFAULT 1,
  qc_length_ok        TINYINT(1) NOT NULL DEFAULT 1,
  input_tokens        INT UNSIGNED NULL,
  cached_input_tokens INT UNSIGNED NULL,
  output_tokens       INT UNSIGNED NULL,
  estimated_cost_thb  DECIMAL(8,4) NULL,
  latency_ms          INT UNSIGNED NULL,
  model               VARCHAR(60)  NOT NULL DEFAULT 'claude-sonnet-4-6',
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_draft_uid (draft_uid),
  KEY idx_drafts_user_created (user_id, created_at DESC),
  KEY idx_drafts_recipient (recipient_name(60)),
  CONSTRAINT fk_drafts_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 5. templates (Phase 3)
-- Reusable starter prompts curated by MARCOM.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS templates (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name            VARCHAR(120) NOT NULL,
  description     VARCHAR(255) NULL,
  task_type       VARCHAR(40)  NOT NULL,
  property_scope  VARCHAR(60)  NULL,                   -- NULL = all properties
  body            MEDIUMTEXT   NOT NULL,
  is_active       TINYINT(1)   NOT NULL DEFAULT 1,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 6. audit_log
-- Append-only. Every meaningful action.
-- DO NOT store full draft bodies here — reference draft_uid instead.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id     BIGINT UNSIGNED NULL,
  action      VARCHAR(60) NOT NULL,
    -- 'login', 'logout', 'generate', 'regenerate',
    -- 'admin_prompt_update', 'admin_template_create',
    -- 'pdpa_delete', 'rate_limit_hit', 'error'
  draft_uid   CHAR(26) NULL,
  severity    ENUM('info','warn','error') NOT NULL DEFAULT 'info',
  metadata    JSON NULL,                               -- token usage, error details, etc.
  ip_address  VARCHAR(45) NULL,
  user_agent  VARCHAR(255) NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_audit_user_created (user_id, created_at DESC),
  KEY idx_audit_action_created (action, created_at DESC),
  CONSTRAINT fk_audit_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Retention job (Phase 2 — set up via Hostinger cron)
-- Runs daily at 03:00 ICT. Deletes drafts older than 18 months.
-- ------------------------------------------------------------
-- DELETE FROM drafts WHERE created_at < NOW() - INTERVAL 18 MONTH;
-- DELETE FROM login_tokens WHERE expires_at < NOW() - INTERVAL 7 DAY;
-- DELETE FROM audit_log WHERE created_at < NOW() - INTERVAL 24 MONTH;

-- ------------------------------------------------------------
-- Seed: pilot users for Rawai (placeholder — replace with real list)
-- ------------------------------------------------------------
-- INSERT INTO users (email, name, role, property) VALUES
--   ('richard.meh@chatrium.com', 'Richard Adrian Mehr', 'general_manager', 'rawai'),
--   ('sakchai.nim@chatrium.com', 'Sakchai Nimdee', 'it_admin', 'rawai'),
--   ('panida.dev@chatrium.com',  'Panida Devahastin', 'marcom_admin', 'rawai');
