#!/usr/bin/env bash
# ============================================================
#  new-customer.sh — Wokeflow SaaS onboarding script
#  Usage: ./scripts/new-customer.sh
#  Or:    SUBDOMAIN=rawai HOTEL_NAME="Chatrium Rawai" ADMIN_EMAIL="..." ./scripts/new-customer.sh
#
#  Requirements:
#    - SSH access to VPS: ssh root@<VPS_IP>
#    - VPS_IP set in env or ~/.wf-config
#    - Docker + Traefik already running on VPS
# ============================================================
set -euo pipefail

# ── Load local config if present ─────────────────────────────
CONFIG_FILE="${HOME}/.wf-config"
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

# ── Colours ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${CYAN}▸${NC} $*"; }
success() { echo -e "${GREEN}✔${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✖${NC}  $*"; exit 1; }

echo -e "\n${BOLD}━━━ Wokeflow — New Customer Setup ━━━${NC}\n"

# ── Required env / prompts ───────────────────────────────────
VPS_IP="${VPS_IP:-}"
if [[ -z "$VPS_IP" ]]; then
  read -rp "VPS IP address: " VPS_IP
fi
[[ -z "$VPS_IP" ]] && error "VPS_IP is required."

VPS_USER="${VPS_USER:-root}"

# Customer details
SUBDOMAIN="${SUBDOMAIN:-}"
if [[ -z "$SUBDOMAIN" ]]; then
  read -rp "Subdomain (e.g. rawai → rawai.wokeflow.net): " SUBDOMAIN
fi
SUBDOMAIN=$(echo "$SUBDOMAIN" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')
[[ -z "$SUBDOMAIN" ]] && error "Subdomain is required."

HOTEL_NAME="${HOTEL_NAME:-}"
if [[ -z "$HOTEL_NAME" ]]; then
  read -rp "Hotel / property name: " HOTEL_NAME
fi
[[ -z "$HOTEL_NAME" ]] && error "Hotel name is required."

ADMIN_EMAIL="${ADMIN_EMAIL:-}"
if [[ -z "$ADMIN_EMAIL" ]]; then
  read -rp "Admin email (for first login): " ADMIN_EMAIL
fi
[[ -z "$ADMIN_EMAIL" ]] && error "Admin email is required."

ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
if [[ -z "$ANTHROPIC_API_KEY" ]]; then
  read -rsp "Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY
  echo
fi
[[ -z "$ANTHROPIC_API_KEY" ]] && error "ANTHROPIC_API_KEY is required."

# SMTP (use Wokeflow shared SMTP or customer's own)
SMTP_HOST="${SMTP_HOST:-smtp.gmail.com}"
SMTP_PORT="${SMTP_PORT:-587}"
SMTP_USER="${SMTP_USER:-}"
if [[ -z "$SMTP_USER" ]]; then
  read -rp "SMTP user email (for magic-link emails) [${SMTP_HOST}]: " SMTP_USER
fi
SMTP_PASS="${SMTP_PASS:-}"
if [[ -z "$SMTP_PASS" ]]; then
  read -rsp "SMTP password / app-password: " SMTP_PASS
  echo
fi

# ── Derived values ────────────────────────────────────────────
DOMAIN_BASE="${DOMAIN_BASE:-wokeflow.net}"
HOST="${SUBDOMAIN}.${DOMAIN_BASE}"
PROJECT_NAME="wf-${SUBDOMAIN}"
DEPLOY_DIR="/opt/wokeflow/${PROJECT_NAME}"
AUTH_URL="https://${HOST}"

# ── Generate secrets ─────────────────────────────────────────
info "Generating secrets…"
AUTH_SECRET=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 40)
MYSQL_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
MYSQL_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

# ── Summary ───────────────────────────────────────────────────
echo
echo -e "${BOLD}── Deployment plan ──────────────────────────────────────${NC}"
echo -e "  Host:        ${GREEN}${HOST}${NC}"
echo -e "  Hotel:       ${HOTEL_NAME}"
echo -e "  Admin email: ${ADMIN_EMAIL}"
echo -e "  VPS:         ${VPS_USER}@${VPS_IP}:${DEPLOY_DIR}"
echo -e "  Project:     ${PROJECT_NAME}"
echo
read -rp "Proceed? [y/N] " CONFIRM
[[ "$CONFIRM" =~ ^[Yy]$ ]] || error "Aborted."

# ── SSH helper ────────────────────────────────────────────────
vps() { ssh -o StrictHostKeyChecking=accept-new "${VPS_USER}@${VPS_IP}" "$@"; }
vps_heredoc() {
  # Usage: vps_heredoc <remote-path> <content>
  ssh -o StrictHostKeyChecking=accept-new "${VPS_USER}@${VPS_IP}" \
    "cat > \"$1\""
}

# ── Create directory on VPS ───────────────────────────────────
info "Creating ${DEPLOY_DIR} on VPS…"
vps "mkdir -p ${DEPLOY_DIR}"

# ── Write docker-compose.yml ──────────────────────────────────
info "Writing docker-compose.yml…"
ssh -o StrictHostKeyChecking=accept-new "${VPS_USER}@${VPS_IP}" "cat > ${DEPLOY_DIR}/docker-compose.yml" <<COMPOSE
# Auto-generated by new-customer.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Customer: ${HOTEL_NAME} (${HOST})

services:
  web:
    image: ghcr.io/enimdee/chatrium-ai:latest
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - app_data:/app/data
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      DATA_DIR: /app/data
      AI_PROVIDER: anthropic
      ANTHROPIC_MODEL: claude-sonnet-4-6
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
      AUTH_SECRET: \${AUTH_SECRET}
      AUTH_URL: \${AUTH_URL}
      ADMIN_EMAIL: \${ADMIN_EMAIL}
      SMTP_HOST: \${SMTP_HOST}
      SMTP_PORT: \${SMTP_PORT}
      SMTP_USER: \${SMTP_USER}
      SMTP_PASS: \${SMTP_PASS}
      AUTH_EMAIL_FROM: \${SMTP_USER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(\`${HOST}\`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3000"
      - "traefik.docker.network=n8n_default"
    networks:
      - n8n_default
      - internal
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chatrium_ai
      MYSQL_USER: chatrium_app
      MYSQL_PASSWORD: \${MYSQL_PASSWORD}
      TZ: Asia/Bangkok
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p\${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  n8n_default:
    external: true
  internal:
    driver: bridge

volumes:
  mysql_data:
  app_data:
COMPOSE

# ── Write .env ────────────────────────────────────────────────
info "Writing .env…"
ssh -o StrictHostKeyChecking=accept-new "${VPS_USER}@${VPS_IP}" "cat > ${DEPLOY_DIR}/.env" <<ENV
# Wokeflow — ${HOTEL_NAME}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — contains secrets

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

AUTH_SECRET=${AUTH_SECRET}
AUTH_URL=${AUTH_URL}
ADMIN_EMAIL=${ADMIN_EMAIL}

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV

vps "chmod 600 ${DEPLOY_DIR}/.env"

# ── Pull image & start ────────────────────────────────────────
info "Pulling latest image…"
vps "cd ${DEPLOY_DIR} && docker compose pull"

info "Starting containers…"
vps "cd ${DEPLOY_DIR} && docker compose up -d"

# ── Health check ──────────────────────────────────────────────
info "Waiting for app to start (30s)…"
sleep 15
for i in {1..5}; do
  HTTP_STATUS=$(curl -sf -o /dev/null -w "%{http_code}" "https://${HOST}/api/healthz" 2>/dev/null || echo "000")
  if [[ "$HTTP_STATUS" == "200" ]]; then
    success "Health check passed (HTTP 200)"
    break
  fi
  warn "Attempt $i/5 — HTTP ${HTTP_STATUS}, retrying in 5s…"
  sleep 5
done

# ── DNS reminder ─────────────────────────────────────────────
echo
echo -e "${BOLD}── DNS (if not already set) ─────────────────────────────${NC}"
echo -e "  Add A record: ${CYAN}${HOST}${NC} → ${VPS_IP}"
echo -e "  Or CNAME:     ${CYAN}${SUBDOMAIN}.${DOMAIN_BASE}${NC} → ${DOMAIN_BASE}"
echo -e "  (Hostinger DNS panel — or use: ./scripts/add-dns.sh ${SUBDOMAIN})"
echo

# ── Save customer record locally ─────────────────────────────
CUSTOMERS_FILE="${SCRIPT_DIR:-$(dirname "$0")}/customers.log"
echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${SUBDOMAIN} | ${HOTEL_NAME} | ${ADMIN_EMAIL} | ${HOST}" >> "$CUSTOMERS_FILE"

# ── Done ──────────────────────────────────────────────────────
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
success "Customer deployed!"
echo
echo -e "  App URL:     ${GREEN}https://${HOST}${NC}"
echo -e "  Admin login: ${ADMIN_EMAIL}"
echo -e "  First login: go to ${CYAN}https://${HOST}/login${NC} and enter the email"
echo -e "               A magic-link will be sent to ${ADMIN_EMAIL}"
echo
echo -e "${YELLOW}Save these secrets somewhere safe (1Password / vault):${NC}"
echo -e "  AUTH_SECRET:         ${AUTH_SECRET}"
echo -e "  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}"
echo -e "  MYSQL_PASSWORD:      ${MYSQL_PASSWORD}"
echo
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
